### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dprutean** [tliron/mongodb-jvm#1]
Hi,
Is this project doing something similar with this one https://github.com/poiati/gmongo for Groovy ?
I am looking for a way in JS Nashorn not to call each time
db.col.find( new BasicDBObject("{name:'bla'}")) 
but simply 
db.col.find( {name:'bla'})) 
Is this possible here ? Or maybe you plan to implement.

**Comment by tliron** [comment]
Yes, this is exactly what this project offers.
